/*
 * main-1.c
 *
 *  Created on: Oct 6, 2023
 *      Author: uykun
 */


/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void UsageFault_Handler_c(uint32_t *pMSP);

int fun_divide(int x , int y){
	return x/y;
}

int main(void)
{
	uint32_t *pSHCSR = (uint32_t*)0xE000ED24;

	*pSHCSR |= (1 << 16);//mem manage
	*pSHCSR |= (1 << 17);//bus fault
	*pSHCSR |= (1 << 18);//usage fault

	//divide by zero trap
	uint32_t *pCCR = (uint32_t*)0xE000ED14;
	*pCCR |= (1 << 4);

	//attemp to divide by zero
	fun_divide(10, 0);

    /* Loop forever */
	for(;;);
}

//Implement fault handlers
void HardFault_Handler(void){
	printf("Exception: HardFault\n");
	while(1);
}
void MemManage_Handler(void){
	printf("Exception: MemManage\n");
	while(1);
}
void BusFault_Handler(void){
	printf("Exception: BusFault\n");
	while(1);
}

__attribute__ ((naked)) void UsageFault_Handler(void){
	__asm ("MRS R0, MSP\n");
	__asm ("B UsageFault_Handler_c\n");
}

void UsageFault_Handler_c(uint32_t* pBaseStackFrame){

	uint32_t *pUFSR = (uint32_t*)0xE000ED2A;
	printf("Exception: UsageFault\n");
	printf("UFSR : %lx\n",(*pUFSR) & 0xFFFF);
	printf("pBaseStackFrame : %p\n",pBaseStackFrame);

	printf("Value of R0 	: %lx\n",pBaseStackFrame[0]);

	printf("Value of R1 	: %lx\n",pBaseStackFrame[1]);

	printf("Value of R2 	: %lx\n",pBaseStackFrame[2]);

	printf("Value of R3 	: %lx\n",pBaseStackFrame[3]);

	printf("Value of R12 	: %lx\n",pBaseStackFrame[4]);

	printf("Value of LR  	: %lx\n",pBaseStackFrame[5]);

	printf("Value of PC 	: %lx\n",pBaseStackFrame[6]);

	printf("Value of XPSR 	: %lx\n",pBaseStackFrame[7]);

	while(1);
}

